### PR TITLE
Skip verify authenticity token

### PR DESCRIPTION
**Pull request by guillaumewrobel**

### CODE REVIEW

**Comment by skatkov** [comment]
What problem are you solving with usage of to_unsafe_h ?

**Comment by guillaumewrobel** [comment]
@skatkov `to_h` needs parameters to be whitelisted (as mentioned [here](https://stackoverflow.com/a/34951198/3149553)).
I didn't take the time with listing all Sendgrid params.

What do you think?

edit: bad link

**Comment by guillaumewrobel** [comment]
Indeed, in Rails 5,

```ruby
@attributes = attributes.with_indifferent_access
```

raises

`NoMethodError (undefined method 'with_indifferent_access' for #<ActionController::Parameters>)` (see [this article](https://blog.bigbinary.com/2016/07/25/parameters-no-longer-inherit-from-hash-with-indifferent-access-in-rails-5.html))

and
```ruby
@attributes = attributes.to_h.with_indifferent_access
```
didn't solve the trick as `to_h` works with whitelisted Parameters.

**Comment by skatkov** [comment]
I don't think that dealing with `ActionController::Parameters` in a model is the right approach. Class name itself suggests that it's a controllers responsibility.

**Pull request closed without merging**
